### ISSUE TITLE
text-2.0 candidate release

### ISSUE THREAD

**Issue by Bodigrim** [haskell/text#385]
I believe current `master` is mature enough to publish a candidate release for user acceptance testing. If there are no other suggestions, I'll upload it on Friday.

**Comment by Bodigrim** [comment]
https://github.com/haskell/text/releases/tag/2.0-rc1
https://hackage.haskell.org/package/text-2.0/candidate

**Comment by AnthonySuper** [comment]
Thank you so much for this!

**Comment by Lysxia** [comment]
Should a candidate release block merging non-critical changes, or are #387 and #388 still okay to merge?

**Comment by Bodigrim** [comment]
There is no change freeze, in fact both #387 and #388 came up during user acceptance testing, feel free to merge.

**Comment by Bodigrim** [comment]
https://github.com/haskell/text/releases/tag/2.0-rc2
https://hackage.haskell.org/package/text-2.0/candidate

**Comment by ethercrow** [comment]
If anyone is having `undefined reference: __get_cpuid_count` error, this might be because your enterprise is still using Ubuntu 16.04 and the corresponding C and C++ compilers.

It's used here: https://github.com/haskell/text/blame/69e3df85662ef430a0c823aa1360d324a8e18bc1/cbits/measure_off.c#L23

**Comment by Bodigrim** [comment]
Ah, good catch! Yeah, it needs `__GNUC__ >= 6` guard, similar to https://github.com/haskell/bytestring/blob/f6065faed6347893beb1b6db88b6788ca15280c1/cbits/fpstring.c#L117. It's a pity that Ubuntu 16.04 is no longer available through GHA.

**Comment by ethercrow** [comment]
Why not reuse CPU capability detection code from simdutf? https://github.com/simdutf/simdutf/blob/8a27811e591c920a31576b43c5d3a6aa7a78ccc7/include/simdutf/internal/isadetection.h

**Comment by Bodigrim** [comment]
General policy is to depend on `simdutf` as little as possible, and this is not even a part of public API.

**Comment by Bodigrim** [comment]
@ethercrow It appears that Ubuntu 16.04 has EOLed in March. I'm ready to accept a patch with `__GNUC__ >= 6` guard from someone able to test it locally, but otherwise will probably release as is, because I have no means to test this configuration.

**Comment by ethercrow** [comment]
Hello, I have another issue building `text-2` on an old-ish OS, this time macOS 10.13 with clang.

C compiler version:

```
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
```

```
Build profile: -w ghc-9.0.1 -O1
In order, the following will be built (use -v for more details):
 - text-2.0 (lib) (first run)
 - text-2.0 (bench:text-benchmarks) (first run)
 - text-2.0 (test:tests) (first run)
Preprocessing library for text-2.0..
Building library for text-2.0..

/var/folders/c2/v6d3nrpd0t14cnr4kxqsv2z00000gn/T/ghc58259_0/ghc_1.s:129:2: error:
     error: instruction requires: AVX-512 ISA
            vmovdqa64       LCPI2_0(%rip), %zmm0 ## zmm0 = [191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191]
            ^
    |
129 |         vmovdqa64       LCPI2_0(%rip), %zmm0 ## zmm0 = [191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191,191]
    |  ^

/var/folders/c2/v6d3nrpd0t14cnr4kxqsv2z00000gn/T/ghc58259_0/ghc_1.s:132:2: error:
     error: instruction requires: AVX-512 ISA
            vmovdqu64       (%rdi), %zmm1
            ^
    |
132 |         vmovdqu64       (%rdi), %zmm1
    |  ^

/var/folders/c2/v6d3nrpd0t14cnr4kxqsv2z00000gn/T/ghc58259_0/ghc_1.s:133:2: error:
     error: instruction requires: AVX-512 BW ISA
            vpcmpgtb        %zmm0, %zmm1, %k0
            ^
    |
133 |         vpcmpgtb        %zmm0, %zmm1, %k0
    |  ^

/var/folders/c2/v6d3nrpd0t14cnr4kxqsv2z00000gn/T/ghc58259_0/ghc_1.s:134:2: error:
     error: instruction requires: AVX-512 BW ISA
            kmovq   %k0, %rax
            ^
    |
134 |         kmovq   %k0, %rax
    |  ^

/var/folders/c2/v6d3nrpd0t14cnr4kxqsv2z00000gn/T/ghc58259_0/ghc_1.s:163:2: error:
     error: instruction requires: AVX-512 BW ISA AVX-512 VL ISA
            vpcmpgtb        LCPI2_1(%rip), %ymm0, %k0
            ^
    |
163 |         vpcmpgtb        LCPI2_1(%rip), %ymm0, %k0
    |  ^

/var/folders/c2/v6d3nrpd0t14cnr4kxqsv2z00000gn/T/ghc58259_0/ghc_1.s:164:2: error:
     error: instruction requires: AVX-512 BW ISA
            kmovd   %k0, %ecx
            ^
    |
164 |         kmovd   %k0, %ecx
    |  ^

/var/folders/c2/v6d3nrpd0t14cnr4kxqsv2z00000gn/T/ghc58259_0/ghc_1.s:178:2: error:
     error: instruction requires: AVX-512 BW ISA AVX-512 VL ISA
            vpcmpgtb        LCPI2_2(%rip), %xmm0, %k0
            ^
    |
178 |         vpcmpgtb        LCPI2_2(%rip), %xmm0, %k0
    |  ^

/var/folders/c2/v6d3nrpd0t14cnr4kxqsv2z00000gn/T/ghc58259_0/ghc_1.s:179:2: error:
     error: instruction requires: AVX-512 BW ISA
            kmovd   %k0, %ecx
            ^
    |
179 |         kmovd   %k0, %ecx
    |  ^
`gcc' failed in phase `Assembler'. (Exit code: 1)
cabal: Failed to build text-2.0 (which is required by bench:text-benchmarks
from text-2.0 and test:tests from text-2.0).
```

**Comment by ethercrow** [comment]
Meanwhile it builds fine on macOS 10.14 with `Apple LLVM version 11.0.0 (clang-1100.0.33.17`.

**Comment by Bodigrim** [comment]
Thanks for the report @ethercrow. I tested Ubuntu 20.04 + llvm 10 + GHC 9.2, and `text` builds just fine, so it is not llvm 10, but rather an outdated version of MacOS is a culprit. Given that MacOS 10.13 EOLed in 2020, I'm ready to accept a patch from an enthusiastic contributor, but otherwise will not block `text-2.0` release on behalf of it.

**Comment by Bodigrim** [comment]
https://hackage.haskell.org/package/text-2.0 is released, identical to rc2.

**Comment by vshabanov** [comment]
@ethercrow, I've just made a fix for the older macOS in #400. Could you, please, test it.

**Comment by ethercrow** [comment]
@vshabanov your patch works for me on 10.13, thank you!

**Comment by phadej** [comment]
On GHA I got an error with GHC-8.2 and GHC-8.0

```
[1 of 1] Compiling Main             ( test/test.hs, /__w/scientific/scientific/dist-newstyle/build/x86_64-linux/ghc-8.0.2/scientific-0.3.7.0/t/test-scientific/build/test-scientific/test-scientific-tmp/Main.o )
Linking /__w/scientific/scientific/dist-newstyle/build/x86_64-linux/ghc-8.0.2/scientific-0.3.7.0/t/test-scientific/build/test-scientific/test-scientific ...
/github/home/.cabal/store/ghc-8.0.2/text-2.0-c46353126c38c0002af2c33e37c7db2e3337f6f1aea8545686900c7ce3780a4e/lib/libHStext-2.0-c46353126c38c0002af2c33e37c7db2e3337f6f1aea8545686900c7ce3780a4e.a(measure_off.o): In function `has_avx512_vl_bw':
measure_off.c:(.text+0x2df): undefined reference to `__get_cpuid_count'
```

https://github.com/basvandijk/scientific/runs/4674626374?check_suite_focus=true

I was able to reproduce in a xenial Docker container following that build job:

```
% docker run -ti --rm buildpack-deps:xenial

apt-get update
apt-get install -y --no-install-recommends gnupg ca-certificates dirmngr curl git software-properties-common
apt-add-repository -y 'ppa:hvr/ghc'
apt-get update
apt-get install -y ghc-8.0.2 cabal-install-3.4
export PATH=/opt/ghc/bin:$PATH

git clone https://github.com/basvandijk/scientific.git
cd scientific

curl -L https://github.com/basvandijk/scientific/pull/84.patch | git am

cabal update
cabal v2-build --disable-tests --disable-benchmarks --dependencies-only -j2
cabal v2-build --disable-tests --disable-benchmarks all
cabal v2-build --enable-tests --disable-benchmarks all
```

**Comment by phadej** [comment]
Ah, I see, it's already reported. Looks like I have some CIs which weren't updated in years.

**Comment by Bodigrim** [comment]
As I said above, if someone feels enthusiastic about supporting old GCCs and adding a CI build to test them, I'm happy to receive a PR.

**Comment by phadej** [comment]
```
Linking C:\WORK\dist-newstyle\build\x86_64-windows\ghc-8.2.2\postgresql-simple-0.6.4\t\test\build\test\test.exe ...
C:\SR\ghc-8.2.2\text-2.0-5e3f12ca9a37edf5a48459f7f3969564285f2adb\lib/libHStext-2.0-5e3f12ca9a37edf5a48459f7f3969564285f2adb.a(measure_off.o):measure_off.c:(.text+0x2da): undefined reference to `__get_cpuid_count'
```

issue happened on oldish Windows used by appveyor: https://ci.appveyor.com/project/phadej/postgresql-simple/builds/42055973/job/66uasdf3b0il1k2j

I hope #401 will fix it.

**Comment by RyanGlScott** [comment]
I ran into a similar issue as https://github.com/haskell/text/issues/385#issuecomment-1003603159 when building `text-show` with `text-2.0` on Windows with GHC 8.2.2 ([CI log](https://ci.appveyor.com/project/RyanGlScott/text-show/builds/42072195/job/a9nh6qrtdpcq7rsc)):

```
[ 8 of 66] Compiling TextShow.GHC.Conc.Windows ( src\TextShow\GHC\Conc\Windows.hs, C:\WORK\dist-newstyle\build\x86_64-windows\ghc-8.2.2\text-show-3.9.5\build\TextShow\GHC\Conc\Windows.o )
ghc.exe:  | C:\SR\ghc-8.2.2\text-2.0-5e3f12ca9a37edf5a48459f7f3969564285f2adb\lib\libHStext-2.0-5e3f12ca9a37edf5a48459f7f3969564285f2adb.a: unknown symbol `__get_cpuid_count'
ghc.exe:  | C:\SR\ghc-8.2.2\text-2.0-5e3f12ca9a37edf5a48459f7f3969564285f2adb\lib\libHStext-2.0-5e3f12ca9a37edf5a48459f7f3969564285f2adb.a: unknown symbol `_hs_text_measure_off'
ghc.exe:  | C:\SR\ghc-8.2.2\text-2.0-5e3f12ca9a37edf5a48459f7f3969564285f2adb\lib\libHStext-2.0-5e3f12ca9a37edf5a48459f7f3969564285f2adb.a: unknown symbol `textzm2zi0zm5e3f12ca9a37edf5a48459f7f3969564285f2adb_DataziTextziLazzy_zdfShowText2_closure'
ghc.exe:  | C:\WORK\dist-newstyle\build\x86_64-windows\ghc-8.2.2\text-show-3.9.5\build\TextShow\Classes.o: unknown symbol `textzm2zi0zm5e3f12ca9a37edf5a48459f7f3969564285f2adb_DataziTextziInternalziBuilder_Buffer_con_info'
```

I tried building the `master` branch of `text` as well, but that failed in a similar fashion:

```
$ cabal build -w ../ghc-8.2.2/bin/ghc
Build profile: -w ghc-8.2.2 -O1
In order, the following will be built (use -v for more details):
 - text-2.0 (test:tests) (first run)
 - text-2.0 (bench:text-benchmarks) (first run)
Preprocessing benchmark 'text-benchmarks' for text-2.0..
Preprocessing test suite 'tests' for text-2.0..
Building test suite 'tests' for text-2.0..
Building benchmark 'text-benchmarks' for text-2.0..
[ 1 of 16] Compiling Tests.Lift       ( tests\Tests\Lift.hs, C:\Users\winferno\Software\text\dist-newstyle\build\x86_64-windows\ghc-8.2.2\text-2.0\t\tests\build\tests\tests-tmp\Tests\Lift.o )
Linking C:\Users\winferno\Software\text\dist-newstyle\build\x86_64-windows\ghc-8.2.2\text-2.0\b\text-benchmarks\build\text-benchmarks\text-benchmarks.exe ...
ghc.exe:  | C:\Users\winferno\Software\text\dist-newstyle\build\x86_64-windows\ghc-8.2.2\text-2.0\build\libHStext-2.0-inplace.a: unknown symbol `__get_cpuid_count'
ghc.exe:  | C:\Users\winferno\Software\text\dist-newstyle\build\x86_64-windows\ghc-8.2.2\text-2.0\build\libHStext-2.0-inplace.a: unknown symbol `_hs_text_measure_off'
ghc.exe: ^^ Could not load 'textzm2zi0zminplace_DataziText_zdfIsStringText_closure', dependency unresolved. See top entry above.


ByteCodeLink.lookupCE
During interactive linking, GHCi couldn't find the following symbol:
  textzm2zi0zminplace_DataziText_zdfIsStringText_closure
This may be due to you not asking GHCi to load extra object files,
archives or DLLs needed by your current session.  Restart GHCi, specifying
the missing library using the -L/path/to/object/dir and -lmissinglibname
flags, or simply by naming the relevant files on the GHCi command line.
Alternatively, this link failure might indicate a bug in GHCi.
If you suspect the latter, please send a bug report to:
  glasgow-haskell-bugs@haskell.org

C:\Users\winferno\Software\text\dist-newstyle\build\x86_64-windows\ghc-8.2.2\text-2.0\build/libHStext-2.0-inplace.a(measure_off.o):measure_off.c:(.text+0x2da): undefined reference to `__get_cpuid_count'
collect2.exe: error: ld returned 1 exit status
`gcc.exe' failed in phase `Linker'. (Exit code: 1)
cabal.exe: Failed to build test:tests from text-2.0.
Failed to build bench:text-benchmarks from text-2.0.
```

I'm unclear if anything can be done about this on `text`'s end, but I wanted to mention it regardless. Let me know if this should be a separate issue.

**Comment by Bodigrim** [comment]
@RyanGlScott is it with the very latest `master`?

**Comment by RyanGlScott** [comment]
Yes, with commit f021db65ba567fe1e885f281b26f7e302ad9a901.

**Comment by RyanGlScott** [comment]
Another way to reproduce the issue is by using this code:

```hs
{-# LANGUAGE TemplateHaskell #-}
module Bug where

import Data.Text as T
import Language.Haskell.TH.Syntax (Lift(..))

f :: Text
f = $(lift T.empty)
```
```
$ cabal repl -b text -w ghc-8.2.2/bin/ghc --constraint="text==2.0.*"
Resolving dependencies...
Build profile: -w ghc-8.2.2 -O1
In order, the following will be built (use -v for more details):
 - fake-package-0 (lib) (first run)
Configuring library for fake-package-0..
Preprocessing library for fake-package-0..
Warning: No exposed modules
GHCi, version 8.2.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from C:\Users\winferno\AppData\Roaming\ghc\ghci.conf
Loaded GHCi configuration from C:\msys64\tmp\cabal-repl.-11260\setcwd.ghci
> :load Bug.hs
[1 of 1] Compiling Bug              ( Bug.hs, interpreted )
ghc.exe:  | C:\Users\winferno\AppData\Roaming\cabal\store\ghc-8.2.2\text-2.0-1d8afaa30ac5f7ba799e1db60e27ec3aa27ff4e9\lib\libHStext-2.0-1d8afaa30ac5f7ba799e1db60e27ec3aa27ff4e9.a: unknown symbol `__get_cpuid_count'
ghc.exe:  | C:\Users\winferno\AppData\Roaming\cabal\store\ghc-8.2.2\text-2.0-1d8afaa30ac5f7ba799e1db60e27ec3aa27ff4e9\lib\libHStext-2.0-1d8afaa30ac5f7ba799e1db60e27ec3aa27ff4e9.a: unknown symbol `_hs_text_measure_off'
ghc.exe: ^^ Could not load 'textzm2zi0zm1d8afaa30ac5f7ba799e1db60e27ec3aa27ff4e9_DataziText_zdfLiftText_closure', dependency unresolved. See top entry above.


ByteCodeLink.lookupCE
During interactive linking, GHCi couldn't find the following symbol:
  textzm2zi0zm1d8afaa30ac5f7ba799e1db60e27ec3aa27ff4e9_DataziText_zdfLiftText_closure
This may be due to you not asking GHCi to load extra object files,
archives or DLLs needed by your current session.  Restart GHCi, specifying
the missing library using the -L/path/to/object/dir and -lmissinglibname
flags, or simply by naming the relevant files on the GHCi command line.
Alternatively, this link failure might indicate a bug in GHCi.
If you suspect the latter, please send a bug report to:
  glasgow-haskell-bugs@haskell.org
```
